// WARNING: DO NOT EDIT.
//
// This file is regenerated by `amplify push`/`amplify publish` (it reads
// SourceDir from amplify/.config/project-config.json) with real values for
// whichever Amplify environment is being deployed. This checked-in copy is
// only a placeholder so local builds work before any environment has been
// provisioned - it intentionally contains no real resource IDs.
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: '',
  aws_user_pools_web_client_id: '',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint: '',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
