// WARNING: this file is regenerated by `amplify push`/`amplify publish` (it
// reads SourceDir from amplify/.config/project-config.json) with real values
// for whichever Amplify environment is being deployed (staging/production
// each get their own). These are the real staging resource ids, committed so
// `ng serve`/local builds have a working Cognito + AppSync backend to talk
// to without needing AWS credentials locally - there's no separate "dev"
// backend provisioned.
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:37c36a78-1f27-4bbc-8542-433c07465911',
  aws_user_pools_id: 'us-east-1_aJ58ggSUE',
  aws_user_pools_web_client_id: '625antflj1v12nhe38t2t3dj67',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint: 'https://hrudpffwcbekdhjcidejgypsra.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
